/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:75a88377-1e5c-47fd-974b-238879ff25f6",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_jIPe6No0z",
    "aws_user_pools_web_client_id": "hi32200uki0rfgsrb75mjajk7",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "api32b07829",
            "endpoint": "https://nweeg7sylh.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
